-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 01:51:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hospital_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hospital_db` ;

-- -----------------------------------------------------
-- Table `hospital_db`.`patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`patients` (
  `patient_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `gender` VARCHAR(10) NOT NULL,
  `language` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`patient_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`admissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`admissions` (
  `admission_id` INT NOT NULL AUTO_INCREMENT,
  `patient_id` INT NOT NULL,
  `admission_date` DATE NOT NULL,
  `discharge_date` DATE NOT NULL,
  `discharge_disposition` VARCHAR(50) NOT NULL,
  `service` VARCHAR(50) NOT NULL,
  `primary_diagnosis` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`admission_id`),
  INDEX `patient_id` (`patient_id` ASC) VISIBLE,
  CONSTRAINT `admissions_ibfk_1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `hospital_db`.`patients` (`patient_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`providers` (
  `provider_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `provider_speciality` VARCHAR(50) NOT NULL,
  `email_address` VARCHAR(100) NULL DEFAULT NULL,
  `phone_number` VARCHAR(15) NULL DEFAULT NULL,
  `date_joined` DATE NOT NULL,
  PRIMARY KEY (`provider_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`appointments` (
  `appointment_id` INT NOT NULL AUTO_INCREMENT,
  `patient_id` INT NOT NULL,
  `doctor_id` INT NOT NULL,
  `appointment_time` DATETIME NOT NULL,
  PRIMARY KEY (`appointment_id`),
  INDEX `patient_id` (`patient_id` ASC) VISIBLE,
  INDEX `doctor_id` (`doctor_id` ASC) VISIBLE,
  CONSTRAINT `appointments_ibfk_1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `hospital_db`.`patients` (`patient_id`),
  CONSTRAINT `appointments_ibfk_2`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `hospital_db`.`providers` (`provider_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`discharges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`discharges` (
  `discharge_id` INT NOT NULL AUTO_INCREMENT,
  `admission_id` INT NOT NULL,
  `patient_id` INT NOT NULL,
  `discharge_date` DATE NOT NULL,
  `discharge_disposition` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`discharge_id`),
  INDEX `admission_id` (`admission_id` ASC) VISIBLE,
  INDEX `patient_id` (`patient_id` ASC) VISIBLE,
  CONSTRAINT `discharges_ibfk_1`
    FOREIGN KEY (`admission_id`)
    REFERENCES `hospital_db`.`admissions` (`admission_id`),
  CONSTRAINT `discharges_ibfk_2`
    FOREIGN KEY (`patient_id`)
    REFERENCES `hospital_db`.`patients` (`patient_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`visits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`visits` (
  `visit_id` INT NOT NULL AUTO_INCREMENT,
  `patient_id` INT NOT NULL,
  `provider_id` INT NOT NULL,
  `date_of_visit` DATE NOT NULL,
  `date_scheduled` DATE NOT NULL,
  `visit_department_id` INT NOT NULL,
  `visit_type` VARCHAR(50) NOT NULL,
  `blood_pressure_systollic` INT NULL DEFAULT NULL,
  `blood_pressure_diastollic` DECIMAL(5,2) NULL DEFAULT NULL,
  `pulse` DECIMAL(5,2) NULL DEFAULT NULL,
  `visit_status` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`visit_id`),
  INDEX `patient_id` (`patient_id` ASC) VISIBLE,
  INDEX `provider_id` (`provider_id` ASC) VISIBLE,
  CONSTRAINT `visits_ibfk_1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `hospital_db`.`patients` (`patient_id`),
  CONSTRAINT `visits_ibfk_2`
    FOREIGN KEY (`provider_id`)
    REFERENCES `hospital_db`.`providers` (`provider_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`ed_visits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`ed_visits` (
  `ed_visit_id` INT NOT NULL AUTO_INCREMENT,
  `visit_id` INT NOT NULL,
  `patient_id` INT NOT NULL,
  `acuity` INT NOT NULL,
  `reason_for_visit` VARCHAR(255) NOT NULL,
  `disposition` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ed_visit_id`),
  INDEX `visit_id` (`visit_id` ASC) VISIBLE,
  INDEX `patient_id` (`patient_id` ASC) VISIBLE,
  CONSTRAINT `ed_visits_ibfk_1`
    FOREIGN KEY (`visit_id`)
    REFERENCES `hospital_db`.`visits` (`visit_id`),
  CONSTRAINT `ed_visits_ibfk_2`
    FOREIGN KEY (`patient_id`)
    REFERENCES `hospital_db`.`patients` (`patient_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hospital_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_db`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('patient', 'doctor', 'admin') NOT NULL,
  `details` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;